[package]
name = "saltpack"
version = "0.1.0"
authors = ["Chu Ka-cheong <kcchu@users.noreply.github.com>"]

[dependencies]
bigint = "4.2.0"
byteorder = "1.1.0"
libc = "0.2.32"
libsodium-sys = "0.0.15"
rand = "0.3.17"
rmp = "0.8.7"
sodiumoxide = "0.0.15"

[dev-dependencies]
rustc-serialize="0.3.19"