[package]
name = "saltpack"
version = "0.1.0"
authors = ["Chu Ka-cheong <kcchu@users.noreply.github.com>"]

[dependencies]
bigint = "4.2.0"
rmp = "0.8.7"
sodiumoxide = "0.0.15"

[dev-dependencies]
rand = "0.3.17"